databases:
  - name: chemical-visualizer-db
    databaseName: chemical_visualizer
    user: chemical_user
    plan: free

services:
  - type: web
    name: chemical-equipment-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn chemical_visualizer.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-visualizer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
